name: coletapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  get:
  provider:
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  easy_splash_screen: ^1.0.4
  image_picker: ^1.0.5
  date_format: ^2.0.7
  image_network: ^2.5.4
  brasil_fields: ^1.14.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:      
  uses-material-design: true
  assets:
    - assets/images/

