// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZtJ9Ba59-PEhvqJehcbaSvwkg9MEeSf4',
    appId: '1:1094794676817:web:c5421829aba5aed5de4670',
    messagingSenderId: '1094794676817',
    projectId: 'coletapp-8022f',
    authDomain: 'coletapp-8022f.firebaseapp.com',
    storageBucket: 'coletapp-8022f.appspot.com',
    measurementId: 'G-5BP17G3Y98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAAweRgkJXc-ohnFeRPZSeCHWD7O8AgBA',
    appId: '1:1094794676817:android:9b5e2a64fc32e87ade4670',
    messagingSenderId: '1094794676817',
    projectId: 'coletapp-8022f',
    storageBucket: 'coletapp-8022f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLqonJz16Zjx2BhtJqNBEUwgkCco3dyfU',
    appId: '1:1094794676817:ios:bee49f4b5f5e48cede4670',
    messagingSenderId: '1094794676817',
    projectId: 'coletapp-8022f',
    storageBucket: 'coletapp-8022f.appspot.com',
    iosClientId: '1094794676817-8fpqq2por8fo6u4mba3goqgpcnucj7se.apps.googleusercontent.com',
    iosBundleId: 'com.example.coletapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLqonJz16Zjx2BhtJqNBEUwgkCco3dyfU',
    appId: '1:1094794676817:ios:bee49f4b5f5e48cede4670',
    messagingSenderId: '1094794676817',
    projectId: 'coletapp-8022f',
    storageBucket: 'coletapp-8022f.appspot.com',
    iosClientId: '1094794676817-8fpqq2por8fo6u4mba3goqgpcnucj7se.apps.googleusercontent.com',
    iosBundleId: 'com.example.coletapp',
  );
}
